apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: default
      server: https://192.168.99.100:8443
    k8sVersion: v1.10.0
    path: default
kind: ksonnet.io/app
name: guestbook
version: 0.0.1
